### ISSUE TITLE
Wrong CSS path in jade file

### ISSUE THREAD

**Issue by artemgurzhii** [travisneilson/DevTipsShowWebsite#2]
You should replace '/' in your path
instead of href="/assets/css/main.css"  use href="assets/css/main.css"

**Comment by artemgurzhii** [comment]
Just find out that you should fix it everywhere

**Comment by travisneilson** [comment]
This would break everything except the homepage. What that leading slash does, it tell the browser to start looking at the root, and then follow the path. If there were no leading slash, it would look relative to the document you are at. For example, the page `devtipsshow.com/jquerycourse` would look for `devtipsshow.com/jquerycourse/assets/css/main.css`, instead of `devtipsshow.com/assets/css/main.css` where it actually is.

Does that make sense?

**Comment by artemgurzhii** [comment]
Sorry, there was my fall. I find this mistake on [travisneilson.com/DevTipsShowWebsite/](http://travisneilson.com/DevTipsShowWebsite/) but instead I should check [devtipsshow.com](devtipsshow.com).
